name: QA

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
#   coverage:
#     name: Code coverage
#     runs-on: ubuntu-latest
#     container:
#       image: xd009642/tarpaulin
#       options: --security-opt seccomp=unconfined
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Generate code coverage
#         run: |
#           cargo tarpaulin --verbose --workspace
